all:
  vars:
    access:
      policies:
        global:
          attachable_access_entity_profiles:
            - name: trunkAep
              tenants:
                RICH:
                  application_profiles:
                    nets:
                      application_epgs:
                        - mode: trunk
                          name: 198.18.103.0
                          vlan_id: 103
                        - mode: trunk
                          name: 198.18.104.0
                          vlan_id: 14
    ansible_command_timeout: 1000
    ansible_connect_timeout: 1000
    ansible_connection: ansible.netcommon.httpapi
    ansible_httpapi_validate_certs: false
    ansible_httpapi_use_ssl: true
    ansible_python_interpreter: "/usr/bin/env python3"
    ansible_user: "admin"
  children:
    aci:
      hosts:
        asgard-apic01.rich.ciscolabs.com:
           ansible_network_os: cisco.aci.aci
        wakanda-apic01.rich.ciscolabs.com:
           ansible_network_os: cisco.aci.aci
